name=rcnRC6502
version=1.0.0
author=YOUNGJIN JOO <neoelec@gmail.com>
maintainer=YOUNGJIN JOO <neoelec@gmail.com>
sentence=Alternative PIO controller firmware library for RC6502 Apple 1 replica
paragraph=Provides 1MHz clock generation, state-machine driven keyboard/video terminal IO, and Micro-SD program loader for RC6502 Apple 1 replica.
category=Device Control
url=https://github.com/neoelec/ino-rc6502-raccoon
architectures=avr
depends=Adafruit MCP23017 Arduino Library, RingBuffer, PetitFatFs, SerialMenuCmd
includes=rcnRC6502.h
